# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cube?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
server:
  port: 8080
